### ISSUE TITLE
Tests are taking too long (they are passing, but taking too long)

### ISSUE THREAD

**Issue by cuducos** [valentinavc/valentina#5]
Any ideas? I might try to use `git revert` to debug that someday.

    Creating test database for alias 'default'...
    ......................
    ----------------------------------------------------------------------
    Ran 22 tests in 32.972s
    
    OK
    Destroying test database for alias 'default'...

Is it taking that long for you all?

**Comment by cuducos** [comment]
Just in case: in a separated branch I used `git revert` and ran the tests until halfway of the git history. Maybe the issue is with the environment, not the codebase. But still not sure.

**Comment by cuducos** [comment]
I tested with SQLite instead of Postgres and the issue persists.

I added this to `settings.py`:

```python
# Use SQLite for quicker tests
if 'test' in sys.argv or 'test_coverage' in sys.argv:
    DATABASES['default'] = dj_database_url.parse(default_db)
print('Using', DATABASES['default']['ENGINE'])
```

But got:

```
Using django.db.backends.sqlite3

Creating test database for alias 'default'...
......................
----------------------------------------------------------------------
Ran 22 tests in 40.461s

OK
Destroying test database for alias 'default'...
```

**Comment by andrealmar** [comment]
`(.venv) ~/dev/valentina (master ✘)✹✭ ᐅ python manage.py test
Creating test database for alias 'default'...
.....................
----------------------------------------------------------------------
Ran 21 tests in 9.512s

OK
Destroying test database for alias 'default'...
`

**Comment by cuducos** [comment]
It seams to be somethings with `User` authentication. With [django-slow-tests](https://github.com/realpython/django-slow-tests) I discovered that all tests involving logins are slow:

```
10 slowest tests:
8.9536s test_logout_link (valentina.app.tests.test_app_view.TestGetWithFemaleUserAuthenticated)
8.3895s test_get (valentina.home.tests.test_home_view.TestGetHomeWithUserAuthenticated)
8.2823s test_get_for_female_user (valentina.app.tests.test_app_view.TestGetWithFemaleUserAuthenticated)
7.0713s test_template (valentina.app.tests.test_app_view.TestGetWithFemaleUserAuthenticated)
6.9849s test_get_for_staff (valentina.app.tests.test_app_view.TestGetWithMaleUserAuthenticated)
0.2576s test_get_for_male_user (valentina.app.tests.test_app_view.TestGetWithMaleUserAuthenticated)
0.2363s test_get (valentina.app.tests.test_logout_view.TestGetLogout)
0.2275s test_get (valentina.app.tests.test_app_view.TestGetWithoutUserAuthenticated)
0.2239s test_login_link (valentina.home.tests.test_home_view.TestGetHomeWithoutUserAuthenticated)
0.1956s test_get (valentina.home.tests.test_home_view.TestGetHomeWithoutUserAuthenticated)
```

It looks like your guess was precise, @gabrielusvicente! Any ideas on how to workaround this issue?

(Thanks @CleitonDeLima for suggesting the right package to track this issue!)

**Comment by gabrielusvicente** [comment]
I tried using plaintext passwords for testing. No success so far.
